INSERT INTO MESSAGES (TEXT) VALUES ('Hello');
INSERT INTO MESSAGES (TEXT) VALUES ('Bye');
INSERT INTO MESSAGES (TEXT) VALUES ('So Long');

INSERT INTO HUMAN (NAME, GENDER, AGE) VALUES ('John', 'M', 20);
INSERT INTO HUMAN (NAME, GENDER, AGE) VALUES ('Jo', 'F', 16);
INSERT INTO HUMAN (NAME, GENDER, AGE) VALUES ('Roxy', 'F', 18);
INSERT INTO HUMAN (NAME, GENDER, AGE) VALUES ('Yoshi', 'M', 19);

INSERT INTO PET (SPECIES, NAME) VALUES ('Cat', 'Fluffy');
INSERT INTO PET (SPECIES, NAME) VALUES ('Bird', 'Brib');
INSERT INTO PET (SPECIES, NAME) VALUES ('Horse', 'Sally');
INSERT INTO PET (SPECIES, NAME) VALUES ('Rabbit', 'Barthalomew');

INSERT INTO HUMAN_PET (HUMAN_ID, PET_ID) VALUES (1, 1);
INSERT INTO HUMAN_PET (HUMAN_ID, PET_ID) VALUES (1, 2);
INSERT INTO HUMAN_PET (HUMAN_ID, PET_ID) VALUES (1, 3);
INSERT INTO HUMAN_PET (HUMAN_ID, PET_ID) VALUES (1, 4);
INSERT INTO HUMAN_PET (HUMAN_ID, PET_ID) VALUES (2, 4);
INSERT INTO HUMAN_PET (HUMAN_ID, PET_ID) VALUES (3, 4);
INSERT INTO HUMAN_PET (HUMAN_ID, PET_ID) VALUES (4, 4);