CREATE TABLE MESSAGES (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  TEXT VARCHAR(256)
);

CREATE TABLE HUMAN (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100),
  GENDER VARCHAR(1),
  AGE INTEGER
);

CREATE TABLE PET (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  SPECIES VARCHAR(100),
  NAME VARCHAR(100)
);

CREATE TABLE HUMAN_PET (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  HUMAN_ID INTEGER,
  PET_ID INTEGER,
  FOREIGN KEY (HUMAN_ID) REFERENCES HUMAN(ID),
  FOREIGN KEY (PET_ID) REFERENCES PET(ID)
);
